name: Deploy to Google Cloud Run

on:
  workflow_dispatch

env:
  SERVICE_NAME: streamlit-app
  REGION: europe-west2

jobs:
  setup-build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to GCP
      run: |
        echo '${{ secrets.GCP_PRIVATE_KEY }}' > private-key.json
        gcloud auth activate-service-account ${{ secrets.GCP_CLIENT_EMAIL }} \
          --key-file=private-key.json \
          --project=${{ secrets.GCP_PROJECT_ID }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Remove old service (if exists)
      run: |-
        if gcloud run services describe $SERVICE_NAME --region=$REGION --platform=managed --quiet 2>/dev/null; then
          gcloud run services delete $SERVICE_NAME \
            --region=$REGION \
            --platform=managed \
            --quiet || true
        fi

    - name: Build and push Docker image
      run: |-
        gcloud builds submit \
          --tag "gcr.io/${{ secrets.GCP_PROJECT_ID }}/$SERVICE_NAME" \
          --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to Cloud Run
      run: |-
        gcloud run deploy $SERVICE_NAME \
          --image "gcr.io/${{ secrets.GCP_PROJECT_ID }}/$SERVICE_NAME" \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated \
          --memory 1Gi \
          --port 8080 \
          --set-env-vars "FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" \
          --set-env-vars "FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}" \
          --set-env-vars "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" \
          --set-env-vars "FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}" \
          --set-env-vars "FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" \
          --set-env-vars "FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}" \
          --set-env-vars "FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }}" \
          --set-env-vars "FIREBASE_DATABASE_URL=${{ secrets.FIREBASE_DATABASE_URL }}"

    - name: Show Service URL
      run: |-
        echo "Service deployed successfully to:"
        gcloud run services describe $SERVICE_NAME \
          --platform managed \
          --region $REGION \
          --format "value(status.url)"